// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Throne.Infrastructure.EfCore;

#nullable disable

namespace Throne.Infrastructure.Migrations
{
    [DbContext(typeof(ThroneDbContext))]
    partial class ThroneDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Throne.Infrastructure.EfCore.Rows.CapabilitiesRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("CurrentVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_version");

                    b.Property<string>("Selections")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("selections");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("capabilities", (string)null);
                });

            modelBuilder.Entity("Throne.Infrastructure.EfCore.Rows.DreamSessionRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DateFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_from");

                    b.Property<string>("DateTo")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_to");

                    b.Property<string>("Host")
                        .HasColumnType("TEXT")
                        .HasColumnName("host");

                    b.Property<string>("ProcessedConversationIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("processed_conversation_ids");

                    b.Property<string>("ProposedPatchIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("proposed_patch_ids");

                    b.Property<string>("Reflection")
                        .HasColumnType("TEXT")
                        .HasColumnName("reflection");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("vendor");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("dream_sessions_created_desc");

                    b.HasIndex("Host", "CreatedAt")
                        .HasDatabaseName("dream_sessions_host_created");

                    b.HasIndex("Vendor", "CreatedAt")
                        .HasDatabaseName("dream_sessions_vendor_created");

                    b.ToTable("dream_sessions", (string)null);
                });

            modelBuilder.Entity("Throne.Infrastructure.EfCore.Rows.GitLabHostSettingsRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("host");

                    b.HasKey("Id");

                    b.ToTable("gitlab_host_settings", (string)null);
                });

            modelBuilder.Entity("Throne.Infrastructure.EfCore.Rows.IntentAttachmentRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CompressionState")
                        .HasColumnType("TEXT")
                        .HasColumnName("compression_state");

                    b.Property<byte[]>("ContentBytes")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("content_bytes");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("DerivedHeight")
                        .HasColumnType("INTEGER")
                        .HasColumnName("derived_height");

                    b.Property<int?>("DerivedWidth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("derived_width");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<string>("IntentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("intent_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.HasKey("Id");

                    b.HasIndex("IntentId")
                        .HasDatabaseName("ix_intent_attachments_intent_id");

                    b.ToTable("intent_attachments", (string)null);
                });

            modelBuilder.Entity("Throne.Infrastructure.EfCore.Rows.IntentCardAttachmentRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER")
                        .HasColumnName("archived");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("availability");

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("board_id");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("card_id");

                    b.Property<string>("CardVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("card_version");

                    b.Property<string>("ColumnTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("column_title");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FetchedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fetched_at");

                    b.Property<string>("IntentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("intent_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<string>("Tracker")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tracker");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IntentId")
                        .HasDatabaseName("ix_intent_card_attachments_intent_id");

                    b.HasIndex("Tracker", "BoardId")
                        .HasDatabaseName("ix_intent_card_attachments_board");

                    b.HasIndex("IntentId", "Tracker", "BoardId", "CardId")
                        .IsUnique()
                        .HasDatabaseName("intent_card_unique");

                    b.ToTable("intent_card_attachments", (string)null);
                });

            modelBuilder.Entity("Throne.Infrastructure.EfCore.Rows.IntentEventRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("IntentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("intent_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT")
                        .HasColumnName("link");

                    b.Property<string>("PeerIntentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("peer_intent_id");

                    b.Property<string>("TextChange")
                        .HasColumnType("TEXT")
                        .HasColumnName("text_change");

                    b.Property<int?>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("PeerIntentId")
                        .HasDatabaseName("ix_intent_events_peer_intent_id");

                    b.HasIndex("IntentId", "CreatedAt")
                        .HasDatabaseName("ix_intent_events_intent_created");

                    b.HasIndex("IntentId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_intent_events_intent_text_version")
                        .HasFilter("kind = 'text_changed'");

                    b.ToTable("intent_events", (string)null);
                });

            modelBuilder.Entity("Throne.Infrastructure.EfCore.Rows.IntentLinkRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("author");

                    b.Property<bool>("Blocking")
                        .HasColumnType("INTEGER")
                        .HasColumnName("blocking");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FromId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("from_id");

                    b.Property<string>("Rationale")
                        .HasColumnType("TEXT")
                        .HasColumnName("rationale");

                    b.Property<string>("ToId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("to_id");

                    b.HasKey("Id");

                    b.HasIndex("FromId")
                        .HasDatabaseName("ix_intent_links_from_id");

                    b.HasIndex("ToId")
                        .HasDatabaseName("ix_intent_links_to_id");

                    b.HasIndex("FromId", "ToId")
                        .IsUnique()
                        .HasDatabaseName("ux_intent_links_from_to");

                    b.ToTable("intent_links", (string)null);
                });

            modelBuilder.Entity("Throne.Infrastructure.EfCore.Rows.IntentPinRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ContextTagId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("context_tag_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("IntentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("intent_id");

                    b.Property<string>("PinSortKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pin_sort_key");

                    b.HasKey("Id");

                    b.HasIndex("IntentId")
                        .HasDatabaseName("ix_intent_pins_intent");

                    b.HasIndex("ContextTagId", "PinSortKey")
                        .HasDatabaseName("ix_intent_pins_context_sort_key");

                    b.HasIndex("IntentId", "ContextTagId")
                        .IsUnique()
                        .HasDatabaseName("ux_intent_pins_intent_context");

                    b.ToTable("intent_pins", (string)null);
                });

            modelBuilder.Entity("Throne.Infrastructure.EfCore.Rows.IntentRepositoryBindingRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CloneError")
                        .HasColumnType("TEXT")
                        .HasColumnName("clone_error");

                    b.Property<string>("CloneStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("clone_status");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("default_branch");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("host");

                    b.Property<string>("IntentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("intent_id");

                    b.Property<string>("LastSeenReviewCommentAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_review_comment_at");

                    b.Property<string>("LastSyncedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<int?>("PullRequestNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pull_request_number");

                    b.Property<string>("PullRequestState")
                        .HasColumnType("TEXT")
                        .HasColumnName("pull_request_state");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("repo");

                    b.Property<string>("ReviewCommentsEtag")
                        .HasColumnType("TEXT")
                        .HasColumnName("review_comments_etag");

                    b.Property<bool>("SuppressMergeAutoClose")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("suppress_merge_auto_close");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkspacePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace_path");

                    b.HasKey("Id");

                    b.HasIndex("IntentId")
                        .HasDatabaseName("intent_id");

                    b.HasIndex("CloneStatus", "PullRequestNumber")
                        .HasDatabaseName("clone_status_pr_number");

                    b.HasIndex("PullRequestState", "LastSyncedAt")
                        .HasDatabaseName("pr_state_last_synced_at");

                    b.HasIndex("IntentId", "Provider", "Host", "Owner", "Repo")
                        .IsUnique()
                        .HasDatabaseName("intent_coordinate_unique");

                    b.ToTable("intent_repository_bindings", (string)null);
                });

            modelBuilder.Entity("Throne.Infrastructure.EfCore.Rows.IntentRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("CleanupLocalStateOnDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("cleanup_local_state_on_done");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_version");

                    b.Property<string>("SortKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sort_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("TagIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tag_ids");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SortKey")
                        .HasDatabaseName("ix_intents_sort_key");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("ix_intents_created_at_id");

                    b.HasIndex("UpdatedAt", "Id")
                        .HasDatabaseName("ix_intents_updated_at_id");

                    b.ToTable("intents", (string)null);
                });

            modelBuilder.Entity("Throne.Infrastructure.EfCore.Rows.IntentStatusChangeRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("from_status");

                    b.Property<string>("IntentId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("intent_id");

                    b.Property<int>("IntentVersionAtWrite")
                        .HasColumnType("INTEGER")
                        .HasColumnName("intent_version_at_write");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("IntentId", "CreatedAt")
                        .HasDatabaseName("ix_intent_status_changes_intent_created");

                    b.ToTable("intent_status_changes", (string)null);
                });

            modelBuilder.Entity("Throne.Infrastructure.EfCore.Rows.IntentTerminalLaunchRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AttachedSkillIds")
                        .HasColumnType("TEXT")
                        .HasColumnName("attached_skill_ids");

                    b.Property<string>("Effort")
                        .HasColumnType("TEXT")
                        .HasColumnName("effort");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mode");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("SelectedSkillIdsByMode")
                        .HasColumnType("TEXT")
                        .HasColumnName("selected_skill_ids_by_mode");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("vendor");

                    b.HasKey("Id");

                    b.ToTable("terminal_launches", (string)null);
                });

            modelBuilder.Entity("Throne.Infrastructure.EfCore.Rows.PromptPartPatchRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AppliedText")
                        .HasColumnType("TEXT")
                        .HasColumnName("applied_text");

                    b.Property<int?>("AppliedVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("applied_version");

                    b.Property<int>("BaseVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("base_version");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DecidedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("decided_at");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("ModeRoles")
                        .HasColumnType("TEXT")
                        .HasColumnName("mode_roles");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("operation");

                    b.Property<string>("PatchText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("patch_text");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rationale");

                    b.Property<string>("RejectComment")
                        .HasColumnType("TEXT")
                        .HasColumnName("reject_comment");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("TargetKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_key");

                    b.Property<string>("TargetScope")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_scope");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("created_desc");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("idempotency_key_unique")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("status_created");

                    b.HasIndex("TargetScope", "TargetKey", "CreatedAt")
                        .HasDatabaseName("target_created");

                    b.ToTable("prompt_part_patches", (string)null);
                });

            modelBuilder.Entity("Throne.Infrastructure.EfCore.Rows.PromptPartRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_version");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("ModeRoles")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mode_roles");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scope");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "Key")
                        .IsUnique()
                        .HasDatabaseName("scope_key_unique");

                    b.ToTable("prompt_parts", (string)null);
                });

            modelBuilder.Entity("Throne.Infrastructure.EfCore.Rows.PullRequestArtifactRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BindingId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("binding_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<string>("HeadSha")
                        .HasColumnType("TEXT")
                        .HasColumnName("head_sha");

                    b.Property<string>("ProducedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("produced_at");

                    b.Property<int>("PullRequestNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pull_request_number");

                    b.Property<string>("Render")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("render");

                    b.Property<string>("ReviewRecommendation")
                        .HasColumnType("TEXT")
                        .HasColumnName("review_recommendation");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("SourceRefs")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_refs");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("BindingId")
                        .HasDatabaseName("binding_id");

                    b.HasIndex("BindingId", "Type")
                        .IsUnique()
                        .HasDatabaseName("binding_type_unique");

                    b.ToTable("pull_request_artifacts", (string)null);
                });

            modelBuilder.Entity("Throne.Infrastructure.EfCore.Rows.RepositoryRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("host");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("repo");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "Host", "Owner", "Repo")
                        .IsUnique()
                        .HasDatabaseName("coordinate_unique");

                    b.ToTable("repositories", (string)null);
                });

            modelBuilder.Entity("Throne.Infrastructure.EfCore.Rows.SkillModeDefaultRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mode");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("skill_id");

                    b.HasKey("Id");

                    b.HasIndex("Mode", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("mode_skill_unique");

                    b.ToTable("skill_mode_defaults", (string)null);
                });

            modelBuilder.Entity("Throne.Infrastructure.EfCore.Rows.TagRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_version");

                    b.Property<string>("DefaultRepositories")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("default_repositories");

                    b.Property<string>("LastAttachedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_attached_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("name_unique");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("created_at_id");

                    b.HasIndex("LastAttachedAt", "Id")
                        .HasDatabaseName("last_attached_at_id")
                        .HasFilter("last_attached_at IS NOT NULL");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Throne.Infrastructure.EfCore.Rows.TaskTrackerConnectionRow", b =>
                {
                    b.Property<string>("Tracker")
                        .HasColumnType("TEXT")
                        .HasColumnName("tracker");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("base_url");

                    b.Property<string>("LastCheckedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_checked_at");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<string>("LastStatus")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_status");

                    b.Property<string>("SelectedBoards")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("selected_boards");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.HasKey("Tracker");

                    b.ToTable("task_tracker_connections", (string)null);
                });

            modelBuilder.Entity("Throne.Infrastructure.EfCore.Rows.TerminalSettingsRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("DefaultVendor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("default_vendor");

                    b.Property<string>("LastModel")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_model");

                    b.Property<string>("LastVendor")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_vendor");

                    b.HasKey("Id");

                    b.ToTable("terminal_settings", (string)null);
                });

            modelBuilder.Entity("Throne.Infrastructure.EfCore.Rows.TextVersionRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int?>("AfterLine")
                        .HasColumnType("INTEGER")
                        .HasColumnName("after_line");

                    b.Property<string>("ChangedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("changed_by");

                    b.Property<string>("InsertText")
                        .HasColumnType("TEXT")
                        .HasColumnName("insert_text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("NewText")
                        .HasColumnType("TEXT")
                        .HasColumnName("new_text");

                    b.Property<string>("OldText")
                        .HasColumnType("TEXT")
                        .HasColumnName("old_text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_kind");

                    b.Property<string>("Snapshot")
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshot");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OwnerKind", "OwnerId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_text_versions_owner_version");

                    b.ToTable("text_versions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
